name: Test Site Build

on:
  push:
    branches:
      - "**"  # Run on all branches
  pull_request:
    branches:
      - "**"  # Run on pull requests to any branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install Anaconda
      - name: Install Anaconda
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://repo.anaconda.com/archive/Anaconda3-2023.07-Linux-x86_64.sh -O anaconda.sh
          bash anaconda.sh -b -p $HOME/anaconda
          eval "$($HOME/anaconda/bin/conda shell.bash hook)"
          conda init
          conda config --set always_yes yes --set changeps1 no

      # Step 3: Run the configuration script
      - name: Run config_conda_env.sh
        run: |
          chmod +x ./config_conda_env.sh
          ./config_conda_env.sh

      # Step 4: Clean up the 'dest' directory if it exists
      - name: Clean 'dest' directory
        run: |
          if [ -d "dest" ]; then
            echo "Removing existing 'dest' directory"
            rm -rf dest
          fi

      # Step 5: Build the site with Grunt
      - name: Build site with Grunt
        run: grunt

      # Step 6: Verify build success
      - name: Verify build
        run: |
          if [ ! -d "dest" ]; then
            echo "Build failed: 'dest' directory not created."
            exit 1
          fi
